### ISSUE TITLE
Click the label will be throw error

### ISSUE THREAD

**Issue by Timson020** [beefe/react-native-picker-android#11]
I use the react-native-picker-android in react-native.
I don't touchmove in app start. I click the will throw the error  in index.js:210

Cannot read property 'value' of undefined

the curItem is undefined

**Comment by Timson020** [comment]
in index.js:153
I add that code 
if (isNaN(this.index)) {
    this.index=0;
    return ;
};
can temporarily fixed this bug

**Comment by xwenliang** [comment]
try this: [react-native-picker](https://github.com/beefe/react-native-picker)
