### ISSUE TITLE
Converting circular structure to json

### ISSUE THREAD

**Issue by gasperz** [beefe/react-native-picker-android#5]
with version 0.3.5 and react-native from master branch.
Issue is reported from PickerAndroid.shouldComponentUpdate (index.js:56)

**Comment by vitalets** [comment]
Also get this issue!
I think it's better to compare state and props explicitly instead of JSON.stringify.
I fixed with:

``` js
shouldComponentUpdate(props, state, context){
    return props.selectedValue !== this.props.selectedValue;
    // return JSON.stringify([props, state, context]) !== JSON.stringify([this.props, this.state, this.context]);
}
```

**Comment by xwenliang** [comment]
sorry for that, fixed.

**Comment by vitalets** [comment]
pls have a look on https://github.com/beefe/react-native-picker-android/commit/cb873caf6e99de2d225194b8925112c30b48c71b#commitcomment-15365534

**Comment by xwenliang** [comment]
I'm terribly sorry, but only check selectedValue was not enough, all of the state that may cause render of the component need to be checked too. https://github.com/beefe/react-native-picker-android/commit/aa7410a4e7bff2fc273c9ab4afe8e866502c626b
Thank you so much!
