### ISSUE TITLE
Using inside a ScrollView

### ISSUE THREAD

**Issue by Hamiltontx** [beefe/react-native-picker-android#7]
I've tried setting the scrollEnabled from the Parent ScrollView when onPanResponderMove to false and onPanResponderRelease to true and work , but, flick a lot, now i've inserted those lines on line 157:

onPanResponderTerminationRequest: () => false,
onStartShouldSetPanResponderCapture: () => true, 
and now it's working very good, but i'm not sure it's the best way.

**Comment by Hamiltontx** [comment]
I've tried setting the scrollEnabled from  the Parent ScrollView when onPanResponderMove to false and onPanResponderRelease to true and work , but, flick a lot, now i've inserted those lines on line 157:

```
onPanResponderTerminationRequest: () => false,
onStartShouldSetPanResponderCapture: () => true, 
```

and now it's working very good, but i'm not sure it's the best way.

**Comment by xwenliang** [comment]
this may be better: [react-native-picker](https://github.com/beefe/react-native-picker)
